### PR TITLE
Proof-of-principle splitable network

### PR DESCRIPTION
**Pull request by bwbush**
- [x] Conway testnet with 9 nodes
- [x] Splitable into 5+4 clusters
- [x] Scripts localize to host machine
- [ ] Nix shell for required tools

### CODE REVIEW

**Comment by bwbush** [comment]
Findings so far:

1. We can create arbitrarily long forks on a split network and then have a battle when the network is unsplit.
2. I verified that nodes stop extending the chain if they see a fork longer than the security parameter.
3. Rootless containers typically cannot manipulate `iptables`. This makes it hard to run these experiments in an upriviledged environment.
4. The `cardano-test` (version 9.2.1) utility crashes and lacks some useful configuration options.

Next steps:

1. Clean up and localize scripts.
2. Write thorough instructions.
3. Collect fork statistics from the logs and draw diagrams.
4. Script and run an experiment for adversarial private network and compare the results to theory.
5. Replace the kludgy `nc` forwarding with wireguard.

**Comment by abailly** [comment]
That's awesome! On my side I have been working in the direction of having a single bootstrap node so that other nodes can join in the "natural" way. From the basis you provide, I feel I would want to:

1. generate all the keys and config files for a single node, holding 100% of delegated stake, but with (a lot of) ADA not staked and available from a faucet
2. add a faucet so that other parties can receive funds and connect their own SPOs
3. provide a wireguard VPN those nodes would use to connect to the network so that an adversary can manipulate routing tables and networking

**Comment by abailly** [comment]
BTW, think you've added inadvertently the log files for all the nodes :)

**Comment by abailly** [comment]
Also, I love the name ❤️

**Comment by bwbush** [comment]
> BTW, think you've added inadvertently the log files for all the nodes :)

🤦 I'll fix that when I squash.

**Comment by bwbush** [comment]
@abailly, what level of review do we need on this?

- [ ] General review of instructions and script?
- [ ] Run network and experiments?

**Comment by abailly** [comment]
I think some documentation to replicate, and actual replication should be just fine. This is already a great first step, and from there we can discuss what direction we want to move tartarus towards. 
I have some spare time tomorrow, will go over this on some machines.

**Review by abailly — APPROVED** [review]
I was able to reproduce some of the experiments: spinning up a cluster, collecting logs, generating graphs, observing clusters' states...
I think this is definitely a great start and something to build upon.

**Pull request merged**
